web:
  image: jwilder/nginx-proxy
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
   - "80:80"

backend:
  build: .
  volumes:
   - .:/code
  links:
   - redis
  environment:
   - PORT_REDIS=6379
   - HOST_REDIS=redis
   - VIRTUAL_HOST=teste.docker
  labels:
   - 'app.environment=${ENV_APP}'
redis:
  image: redis
  volumes:
   - dados_${ENV_APP}:/data
  labels:
   - 'app.environment=${ENV_APP}'
